name: "Linux"

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup C++ environment
      run: |
        sudo apt update && sudo apt install -y g++ libomp-dev libopenblas-dev libmkl-dev intel-mkl
        
    - name: Install Gtest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake .. -DBUILD_GMOCK=OFF
        make -j
        sudo make install
      
    - name: Git clone TTM repo
      run: |
        cd ${GITHUB_WORKSPACE}
        git clone https://github.com/bassoy/ttm.git

    - name: Build and run tests
      run: |
        cd ttm/test
        make -j
        ./bin/main      
        
